export const compliments = [
    "Keep going!! 💯", 
    "Ohhh Boy!! 😤", 
    "Too sharp!!! 💯", 
    "Out of this world! 👽",
    "Superstar!!! ⭐", 
    "Don't playyyyy!! 🤩", 
    "You're almost there!! 💪", 
    "Just WOW!!! 🔥", 
    "Let's go!! 👻", 
    "Keep it up!!! 👏", 
    "Incredible!! 🔥", 
    "Amazing work!! ✨", 
    "Super speed!! 😎"
];

export const gameAcronyms = [
    {
        acronym: "FAIL",
        options: [
            "Forget",
            "Forgive",
            "Failure",
            "Attempt",
            "In",
            "Learning",
            "First",
            "Impact",
            "Launch",
            "Forward",
            "Aim",
            "Improve",
        ],
        correct: ["First", "Attempt", "In", "Learning"],
    },
    {
        acronym: "MAD",
        options: [
            "Make",
            "Move",
            "Motivate",
            "Alter",
            "Difference",
            "A",
            "Achieve",
            "Aspire",
            "Act",
            "Mind",
            "Mark",
            "Develop",
        ],
        correct: ["Make", "A", "Difference"],
    },
    {
        acronym: "HARD",
        options: [
            "Ambitious",
            "Driven",
            "Hopeful",
            "Resilient",
            "Reinvent",
            "Dream",
            "Dare",
            "Diligent",
            "Adapt",
            "Rise",
            "Heart",
            "Action",
        ],
        correct: ["Hopeful", "Ambitious", "Resilient", "Driven"],
    },
    {
        acronym: "FEAR",
        options: [
            "Face",
            "And",
            "Rise",
            "Expect",
            "Revive",
            "Accept",
            "Everything",
            "Adapt",
            "Fail",
            "Action",
            "Endure",
            "Realize",
        ],
        correct: ["Face", "Everything", "And", "Rise"],
    },
    {
        acronym: "PAIN",
        options: [
            "Positive",
            "Attitude",
            "Increases",
            "Awareness",
            "Inspire",
            "Now",
            "Navigate",
            "Apply",
            "Integrity",
            "Persistence",
            "Allow",
            "Impact",
        ],
        correct: ["Positive", "Attitude", "Increases", "Now"],
    },
    {
        acronym: "RAGE",
        options: [
            "Rise",
            "Above",
            "Revive",
            "Aspire",
            "Generate",
            "Grow",
            "Empower",
            "Achieve",
            "Everyday",
            "Adapt",
            "Guide",
            "Explore",
        ],
        correct: ["Rise", "Above", "Grow", "Everyday"],
    },
    {
        acronym: "SICK",
        options: [
            "Strong",
            "Sustain",
            "Innovate",
            "Change",
            "Inspired",
            "Courageous",
            "Keen",
            "Knowledge",
            "Support",
            "Care",
            "See",
            "Kind",
        ],
        correct: ["Strong", "Inspired", "Courageous", "Kind"],
    },
    {
        acronym: "LOSER",
        options: [
            "Onward",
            "Every",
            "Result",
            "Resilience",
            "Learning",
            "Opportunity",
            "Explore",
            "Succeed",
            "Open",
            "Effort",
            "Rise",
            "Risk",
        ],
        correct: ["Learning", "Opportunity", "Succeed", "Effort", "Result"],
    },
    {
        acronym: "WIMP",
        options: [
            "Mature",
            "Wise",
            "Positive",
            "Willing",
            "Inspire",
            "Intelligent",
            "Motivated",
            "Persevere",
            "Will",
            "Influence",
            "Perfect",
            "Master",
        ],
        correct: ["Wise", "Intelligent", "Motivated", "Persevere"],
    },
    {
        acronym: "GUILT",
        options: [
            "Great",
            "In",
            "Learning",
            "Generate",
            "Uplift",
            "Understanding",
            "Inspire",
            "Transform",
            "Grow",
            "Unify",
            "Lead",
            "Improve",
        ],
        correct: ["Great", "Understanding", "Inspire", "Lead", "Transform"],
    },
    {
        acronym: "CRY",
        options: [
            "Courageous",
            "Resilient",
            "Youth",
            "Create",
            "Reflect",
            "Yield",
            "Reach",
            "Yearn",
            "Root",
            "Year",
            "Change",
            "Connect",
        ],
        correct: ["Courageous", "Resilient", "Yearn"],
    },
    {
        acronym: "STUCK",
        options: [
            "Tenacious",
            "Unique",
            "Courageous",
            "Kind",
            "Seek",
            "Strong",
            "Understand",
            "Communicate",
            "Support",
            "Teach",
            "Stand",
            "Trust",
        ],
        correct: ["Strong", "Tenacious", "Unique", "Courageous", "Kind"],
    },
    {
        acronym: "BOLD",
        options: [
            "Brave",
            "Optimistic",
            "Lively",
            "Determined",
            "Bold",
            "Open",
            "Learn",
            "Drive",
            "Believe",
            "Order",
            "Lift",
            "Organize",
        ],
        correct: ["Brave", "Optimistic", "Lively", "Determined"],
    },
    {
        acronym: "RISK",
        options: [
            "Strong",
            "Knowledgeable",
            "Reflect",
            "Innovate",
            "Strategize",
            "Keep",
            "Resilient",
            "Invest",
            "Safe",
            "Inspired",
            "Insight",
            "Kick",
        ],
        correct: ["Resilient", "Inspired", "Strong", "Knowledgeable"],
    },
    {
        acronym: "LOVE",
        options: [
            "Open",
            "Learn",
            "Everyone",
            "Lend",
            "Observe",
            "Vibe",
            "Lift",
            "Offer",
            "Endure",
            "Look",
            "Value",
            "Express",
        ],
        correct: ["Learn", "Open", "Value", "Everyone"],
    },
    {
        acronym: "TIME",
        options: [
            "Innovate",
            "Tackle",
            "Inspire",
            "Manage",
            "Empower",
            "Team",
            "Integrity",
            "Move",
            "Motivate",
            "Think",
            "Meet",
            "Trust",
        ],
        correct: ["Trust", "Innovate", "Motivate", "Empower"],
    },
    {
        "acronym": "LOST",
        "options": [
            "Learn",
            "Observe",
            "Strengthen",
            "Trust",
            "Look",
            "Open",
            "Strive",
            "Transform"
        ],
        "correct": ["Learn", "Observe", "Strengthen", "Trust"]
    },

    {
        "acronym": "STRESS",
        "options": [
            "Strength",
            "Trust",
            "Resilience",
            "Empathy",
            "Support",
            "Simplicity",
            "Service",
            "Strive"
        ],
        "correct": ["Strength", "Trust", "Resilience", "Empathy", "Support", "Service"]
    },
    {
        "acronym": "SHAME",
        "options": [
            "Self-Love",
            "Honor",
            "Authenticity",
            "Mindfulness",
            "Empathy",
            "Support",
            "Acceptance",
            "Motivate"
        ],
        "correct": ["Self-Love", "Honor", "Authenticity", "Mindfulness", "Empathy"]
    },
    {
        "acronym": "TIRED",
        "options": [
            "Trust",
            "Inspire",
            "Rest",
            "Energize",
            "Develop",
            "Together",
            "Reflect",
            "Empower"
        ],
        "correct": ["Trust", "Inspire", "Rest", "Energize", "Develop"]
    },
    {
        "acronym": "SAD",
        "options": [
            "Smile",
            "Appreciate",
            "Dream",
            "Support",
            "Accept",
            "Develop",
            "Achieve",
            "Shine"
        ],
        "correct": ["Smile", "Appreciate", "Dream"]
    },
    {
        "acronym": "JEALOUS",
        "options": [
            "Joyful",
            "Energetic",
            "Ambitious",
            "Loving",
            "Open",
            "Unstoppable",
            "Strong",
            "Passionate",
            "Focused",
            "Inspired",
            "Creative",
            "Resilient"
        ],
        "correct": ["Joyful", "Energetic", "Ambitious", "Loving", "Open", "Unstoppable", "Strong"]
    },
    {
        "acronym": "BREAK",
        "options": [
            "Brave",
            "Resilient",
            "Empowered",
            "And",
            "Knowledgeable",
            "Innovative",
            "Strong",
            "Creative",
            "Optimistic",
            "Hopeful",
            "Focused",
            "Driven"
        ],
        "correct": ["Brave", "Resilient", "Empowered", "And", "Knowledgeable"]
    },
    {
        "acronym": "FLOP",
        "options": [
            "Flourishing",
            "Learning",
            "Open-minded",
            "Persistent",
            "Strong",
            "Creative",
            "Resilient",
            "Optimistic",
            "Brave",
            "Focused",
            "Hopeful",
            "Focused"
        ],
        "correct": ["Flourishing", "Learning", "Open-minded", "Persistent"]
    },
    {
        "acronym": "WASTE",
        "options": [
            "Wise",
            "Ambitious",
            "Strong",
            "Tenacious",
            "Enthusiastic",
            "Purposeful",
            "Creative",
            "Determined",
            "Empowered",
            "Optimistic",
            "Hopeful",
            "Focused"
        ],
        "correct": ["Wise", "Ambitious", "Strong", "Tenacious", "Enthusiastic"]
    },
    {
        "acronym": "THREAT",
        "options": [
            "Tenacious",
            "Hopeful",
            "Resilient",
            "Energized",
            "Ambitious",
            "Thriving",
            "Creative",
            "Focused",
            "Driven",
            "Determined",
            "Innovative",
            "Inspirational"
        ],
        "correct": ["Tenacious", "Hopeful", "Resilient", "Energized", "Ambitious", "Thriving"]
    },
    {
        "acronym": "CURSE",
        "options": [
            "Courageous",
            "Unstoppable",
            "Resilient",
            "Strong",
            "Empowered",
            "Optimistic",
            "Creative",
            "Focused",
            "Driven",
            "Brave",
            "Ambitious",
            "Hopeful"
        ],
        "correct": ["Courageous", "Unstoppable", "Resilient", "Strong", "Empowered"]
    },
    {
        "acronym": "BLAME",
        "options": [
            "Brave",
            "Loving",
            "Ambitious",
            "Motivated",
            "Evolving",
            "Creative",
            "Resilient",
            "Focused",
            "Determined",
            "Optimistic",
            "Persistent",
            "Passionate"
        ],
        "correct": ["Brave", "Loving", "Ambitious", "Motivated", "Evolving"]
    },
    {
        "acronym": "ENVY",
        "options": [
            "Energized",
            "Nourished",
            "Visionary",
            "Youthful",
            "Optimistic",
            "Creative",
            "Determined",
            "Resilient",
            "Focused",
            "Empowered",
            "Hopeful",
            "Ambitious"
        ],
        "correct": ["Energized", "Nourished", "Visionary", "Youthful"]
    },
    {
        "acronym": "PANIC",
        "options": [
            "Purposeful",
            "Adaptable",
            "Nurturing",
            "Inspiring",
            "Compassionate",
            "Resilient",
            "Focused",
            "Creative",
            "Strong",
            "Hopeful",
            "Brave",
            "Motivated"
        ],
        "correct": ["Purposeful", "Adaptable", "Nurturing", "Inspiring", "Compassionate"]
    }
];